@AbapCatalog.viewEnhancementCategory: [#PROJECTION_LIST,#UNION]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'True-up Data'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
@Metadata.allowExtensions: true
define view entity /ESRCC/I_TRUEUP_DATA
  as select from /esrcc/trueup
{
  key uuid                as Uuid,
  key cc_uuid             as CcUuid,
  key srv_uuid            as SrvUuid,
      ryear               as Ryear,
      poper               as Poper,
      recalrefpoper       as Recalrefpoper,
      fplv                as Fplv,
      sysid               as Sysid,
      legalentity         as Legalentity,
      ccode               as Ccode,
      costobject          as Costobject,
      costcenter          as Costcenter,
      functionalarea      as Functionalarea,
      businessdivision    as Businessdivision,
      profitcenter        as Profitcenter,
      serviceproduct      as Serviceproduct,
      servicetype         as Servicetype,
      transactiongroup    as Transactiongroup,
      chargeout           as Chargeout,
      receiversysid       as Receiversysid,
      receivingentity     as Receivingentity,
      receivercompanycode as Receivercompanycode,
      receivercostobject  as Receivercostobject,
      receivercostcenter  as Receivercostcenter,
      'L'                 as CurrencyType,
      localcurr           as Currency,      
      amount_l            as Amount,     
      status              as Status,
      exchdate            as Exchdate,
      invoiceuuid         as Invoiceuuid,
      invoicenumber       as Invoicenumber,
      invoicestatus       as Invoicestatus,
      invoicingcurrency   as Invoicingcurrency,
      erpsalesorder       as Erpsalesorder,
      contractid          as Contractid,
      postingdate         as Postingdate,
      postingperiod       as Postingperiod,
      erpflag             as Erpflag,
      created_by          as CreatedBy,
      created_at          as CreatedAt,
      last_changed_by     as LastChangedBy,
      last_changed_at     as LastChangedAt
}

union

  select from /esrcc/trueup
{
  key uuid                as Uuid,
  key cc_uuid             as CcUuid,
  key srv_uuid            as SrvUuid,
      ryear               as Ryear,
      poper               as Poper,
      recalrefpoper       as Recalrefpoper,
      fplv                as Fplv,
      sysid               as Sysid,
      legalentity         as Legalentity,
      ccode               as Ccode,
      costobject          as Costobject,
      costcenter          as Costcenter,
      functionalarea      as Functionalarea,
      businessdivision    as Businessdivision,
      profitcenter        as Profitcenter,
      serviceproduct      as Serviceproduct,
      servicetype         as Servicetype,
      transactiongroup    as Transactiongroup,
      chargeout           as Chargeout,
      receiversysid       as Receiversysid,
      receivingentity     as Receivingentity,
      receivercompanycode as Receivercompanycode,
      receivercostobject  as Receivercostobject,
      receivercostcenter  as Receivercostcenter,
      'I'                 as CurrencyType,
      localcurr           as Currency,      
      amount_l            as Amount,      
      status              as Status,
      exchdate            as Exchdate,
      invoiceuuid         as Invoiceuuid,
      invoicenumber       as Invoicenumber,
      invoicestatus       as Invoicestatus,
      invoicingcurrency   as Invoicingcurrency,
      erpsalesorder       as Erpsalesorder,
      contractid          as Contractid,
      postingdate         as Postingdate,
      postingperiod       as Postingperiod,
      erpflag             as Erpflag,
      created_by          as CreatedBy,
      created_at          as CreatedAt,
      last_changed_by     as LastChangedBy,
      last_changed_at     as LastChangedAt
}

union

select from /esrcc/trueup
{
  key uuid                as Uuid,
  key cc_uuid             as CcUuid,
  key srv_uuid            as SrvUuid,
      ryear               as Ryear,
      poper               as Poper,
      recalrefpoper       as Recalrefpoper,
      fplv                as Fplv,
      sysid               as Sysid,
      legalentity         as Legalentity,
      ccode               as Ccode,
      costobject          as Costobject,
      costcenter          as Costcenter,
      functionalarea      as Functionalarea,
      businessdivision    as Businessdivision,
      profitcenter        as Profitcenter,
      serviceproduct      as Serviceproduct,
      servicetype         as Servicetype,
      transactiongroup    as Transactiongroup,
      chargeout           as Chargeout,
      receiversysid       as Receiversysid,
      receivingentity     as Receivingentity,
      receivercompanycode as Receivercompanycode,
      receivercostobject  as Receivercostobject,
      receivercostcenter  as Receivercostcenter,
      'G'                 as CurrencyType,
      groupcurr           as Currency,      
      amount_g            as Amount,      
      status              as Status,
      exchdate            as Exchdate,
      invoiceuuid         as Invoiceuuid,
      invoicenumber       as Invoicenumber,
      invoicestatus       as Invoicestatus,
      invoicingcurrency   as Invoicingcurrency,
      erpsalesorder       as Erpsalesorder,
      contractid          as Contractid,
      postingdate         as Postingdate,
      postingperiod       as Postingperiod,
      erpflag             as Erpflag,
      created_by          as CreatedBy,
      created_at          as CreatedAt,
      last_changed_by     as LastChangedBy,
      last_changed_at     as LastChangedAt
}
